# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-devel
    template: publicapi-indexer-devel
  name: publicapi-indexer-devel
objects:
  # Job (devel)
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: publicapi-indexer-job-devel
      labels:
        app: publicapi-indexer-devel
      annotations:
        description: ElasticSearch indexer for Public devel branch
    spec:
      template:
        spec:
          containers:
            - name: publicapi-indexer-container-devel
              image: publicapi-indexer-devel
              imagePullPolicy: Always
              env:
                - name: "ELASTICSEARCH__URL"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__URL"
                - name: "ELASTICSEARCH__USERNAME"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__USERNAME"
                - name: "ELASTICSEARCH__PASSWORD"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__PASSWORD"
                - name: "dbconnectionstring"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: dbconnectionstring
                - name: "dbconnectionstring"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-pilot
                        key: dbconnectionstring
                - name: "IndexNames__Api.Models.FundingCall.FundingCall"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-pilot
                        key: "IndexNames__Api.Models.FundingCall.FundingCall"
                - name: "IndexNames__Api.Models.FundingDecision.FundingDecision"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-pilot
                        key: "IndexNames__Api.Models.FundingDecision.FundingDecision"
          restartPolicy: Never

  # ImageStream (development)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-devel
      labels:
        app: publicapi-indexer-devel
    spec:
        lookupPolicy:
            local: true

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: devel
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-devel:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
