# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-devel
    template: publicapi-indexer-devel
  name: publicapi-indexer-devel
objects:
  # Job (devel)
  - apiVersion: v1
    kind: Job
    metadata:
      name: publicapi-indexer-job-devel
      labels:
        app: publicapi-indexer-devel
      annotations:
        description: ElasticSearch indexer for Public devel branch
    spec:
      # ports:
      #   - name: publicapi-api-port-devel
      #     port: 8080
      #     targetPort: 8080
      selector:
        depcfg: publicapi-indexer-depcfg-devel
      parallelism: 1
      completions: 1

  # ImageStream (development)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-devel
      labels:
        app: publicapi-indexer-devel

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: devel
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-devel:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4

  # Deployment config (development)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: publicapi-indexer-deployment-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      selector:
        app: publicapi-indexer-devel
        depcfg: publicapi-indexer-depcfg-devel
      template:
        metadata:
          labels:
            app: publicapi-indexer-devel
            depcfg: publicapi-indexer-depcfg-devel
        spec:
          containers:
            - name: publicapi-indexer-container-devel
              image: publicapi/publicapi-indexer-devel
              imagePullPolicy: Always
              # ports:
              #   - containerPort: 8080
              #     protocol: TCP
              restartPolicy: Never
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - publicapi-indexer-container-devel
            from:
              kind: ImageStreamTag
              name: publicapi-indexer-devel:latest
      strategy:
        type: Rolling