# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-devel
    template: publicapi-indexer-devel
  name: publicapi-indexer-devel
objects:
  # Recurring CronJob (devel)
  # Indexes db entities to ElasticSearch.
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: publicapi-indexer-cronjob-devel
    spec:
      schedule: "0 1 * * *" # every day at 01:00 UTC
      concurrencyPolicy: "Forbid"
      startingDeadlineSeconds: 300 # Can start 5 minutes after the schedule
      suspend: false
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 3
      jobTemplate:
        spec:
          activeDeadlineSeconds: 2400 # Can run for 40 minutes
          template:
            spec:
              containers:
                - name: publicapi-indexer-container-devel
                  image: publicapi-indexer-devel
                  imagePullPolicy: Always
                  env:
                    - name: "ELASTICSEARCH__PASSWORD"
                      valueFrom:
                        secretKeyRef:
                          name: publicapi-api-secret-devel
                          key: "ELASTICSEARCH__PASSWORD"
                    - name: "dbconnectionstring"
                      valueFrom:
                        secretKeyRef:
                          name: publicapi-api-secret-devel
                          key: dbconnectionstring
                    - name: "ELASTICSEARCH__URL"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "ELASTICSEARCH__URL"
                    - name: "ELASTICSEARCH__USERNAME"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "ELASTICSEARCH__USERNAME"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                    - name: "Serilog__MinimumLevel__Default"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "Serilog__MinimumLevel__Default"
                    - name: "Serilog__WriteTo__HttpSink__Args__requestUri"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "Serilog__WriteTo__HttpSink__Args__requestUri"
                    - name: "Serilog__Properties__WoodLogProjectNumber"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "Serilog__Properties__WoodLogProjectNumber"
                    - name: "Serilog__Properties__WoodLogRetentionMonths"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "Serilog__Properties__WoodLogRetentionMonths"
                    - name: "Serilog__Properties__WoodLogUsecase"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "Serilog__Properties__WoodLogUsecase"
                    - name: "QueryTimeout"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-devel
                          key: "QueryTimeout"
              restartPolicy: Never
  # ImageStream (development)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      lookupPolicy:
        local: true

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: devel
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-devel:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
