# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-devel
    template: publicapi-indexer-devel
  name: publicapi-indexer-devel
objects:
  # Single-run Job (devel)
  # Use this job to index entities to ElasticSearch manually when needed.
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: publicapi-indexer-job-devel
      labels:
        app: publicapi-indexer-devel
      annotations:
        description: ElasticSearch indexer for Public devel branch
    spec:
      template:
        spec:
          containers:
            - name: publicapi-indexer-container-devel
              image: publicapi-indexer-devel
              imagePullPolicy: Always
              env:
                - name: "ELASTICSEARCH__URL"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__URL"
                - name: "ELASTICSEARCH__USERNAME"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__USERNAME"
                - name: "ELASTICSEARCH__PASSWORD"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: "ELASTICSEARCH__PASSWORD"
                - name: "dbconnectionstring"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-devel
                        key: dbconnectionstring
                - name: "IndexNames__Api.Models.FundingCall.FundingCall"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-devel
                        key: "IndexNames__Api.Models.FundingCall.FundingCall"
                - name: "IndexNames__Api.Models.FundingDecision.FundingDecision"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-devel
                        key: "IndexNames__Api.Models.FundingDecision.FundingDecision"
                - name: "IndexNames__Api.Models.Infrastructure.Infrastructure"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-devel
                        key: "IndexNames__Api.Models.Infrastructure.Infrastructure"
                - name: "IndexNames__Api.Models.Organization.Organization"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-devel
                        key: "IndexNames__Api.Models.Organization.Organization"
                - name: "IndexNames__Api.Models.ResearchDataset.ResearchDataset"
                  valueFrom:
                    configMapKeyRef:
                        name: publicapi-api-config-devel
                        key: "IndexNames__Api.Models.ResearchDataset.ResearchDataset"
          restartPolicy: Never