# This file is part of the research.fi api
#
# Copyright 2023 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-production
    template: publicapi-indexer-production
  name: publicapi-indexer-production
objects:
  # Recurring CronJob (production)
  # Indexes db entities to ElasticSearch.
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: publicapi-indexer-cronjob-production
    spec:
      schedule: "0 1 * * *"       
      concurrencyPolicy: "Forbid"  
      startingDeadlineSeconds: 200  
      suspend: false                
      successfulJobsHistoryLimit: 3 
      failedJobsHistoryLimit: 3     
      jobTemplate:                  
        spec:
            template:
                spec:
                  containers:
                    - name: publicapi-indexer-container-production
                      image: publicapi-indexer-production
                      imagePullPolicy: Always
                      env:
                        - name: "ELASTICSEARCH__PASSWORD"
                          valueFrom:
                            secretKeyRef:
                                name: publicapi-api-secret-production
                                key: "ELASTICSEARCH__PASSWORD"
                        - name: "dbconnectionstring"
                          valueFrom:
                            secretKeyRef:
                                name: publicapi-api-secret-production
                                key: dbconnectionstring
                        - name: "ELASTICSEARCH__URL"
                          valueFrom:
                            configMapKeyRef:
                              name: publicapi-api-config-production
                              key: "ELASTICSEARCH__URL"
                        - name: "ELASTICSEARCH__USERNAME"
                          valueFrom:
                            configMapKeyRef:
                              name: publicapi-api-config-production
                              key: "ELASTICSEARCH__USERNAME"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                          valueFrom:
                            configMapKeyRef:
                                name: publicapi-api-config-production
                                key: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                          valueFrom:
                            configMapKeyRef:
                                name: publicapi-api-config-production
                                key: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                          valueFrom:
                            configMapKeyRef:
                                name: publicapi-api-config-production
                                key: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                          valueFrom:
                            configMapKeyRef:
                                name: publicapi-api-config-production
                                key: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                          valueFrom:
                            configMapKeyRef:
                                name: publicapi-api-config-production
                                key: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                        - name: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                          valueFrom:
                            configMapKeyRef:
                              name: publicapi-api-config-production
                              key: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                        - name: "Serilog__MinimumLevel__Default"
                          valueFrom:
                            configMapKeyRef:
                              name: publicapi-api-config-production
                              key: "Serilog__MinimumLevel__Default"
                        - name: "Serilog__WriteTo__OpenSearchSink__Args__nodeUris"
                          valueFrom:
                            configMapKeyRef:
                              name: publicapi-api-config-production
                              key: "Serilog__WriteTo__OpenSearchSink__Args__nodeUris"
                  restartPolicy: Never
  # ImageStream (production)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-production
      labels:
        app: publicapi-indexer-production
    spec:
        lookupPolicy:
            local: true

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-production
      labels:
        app: publicapi-indexer-production
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: master
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-production:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
