# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-pilot
    template: publicapi-indexer-pilot
  name: publicapi-indexer-pilot
objects:
  # Job (pilot)
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: publicapi-indexer-job-pilot
      labels:
        app: publicapi-indexer-pilot
      annotations:
        description: ElasticSearch indexer for Public api pilot branch
    spec:
      template:
        spec:
          containers:
            - name: publicapi-indexer-container-pilot
              image: publicapi-indexer-pilot
              imagePullPolicy: Always
              env:
                - name: "ELASTICSEARCH__URL"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-pilot
                        key: "ELASTICSEARCH__URL"
                - name: "ELASTICSEARCH__USERNAME"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-pilot
                        key: "ELASTICSEARCH__USERNAME"
                - name: "ELASTICSEARCH__PASSWORD"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-pilot
                        key: "ELASTICSEARCH__PASSWORD"
                - name: "dbconnectionstring"
                  valueFrom:
                    secretKeyRef:
                        name: publicapi-api-secret-pilot
                        key: dbconnectionstring
          restartPolicy: Never

  # ImageStream (pilot)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-pilot
      labels:
        app: publicapi-indexer-pilot
    spec:
        lookupPolicy:
            local: true

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-pilot
      labels:
        app: publicapi-indexer-pilot
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: pilot
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-pilot:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
