# This file is part of the research.fi api
#
# Copyright 2022 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-api-pilot
    template: publicapi-api-pilot
  name: publicapi-api-pilot
objects:
  # Service (pilot)
  - apiVersion: v1
    kind: Service
    metadata:
      name: publicapi-api-service-pilot
      labels:
        app: publicapi-api-pilot
      annotations:
        description: Public api service for pilot branch
    spec:
      ports:
        - name: publicapi-api-port-pilot
          port: 8080
          targetPort: 8080
      selector:
        depcfg: publicapi-api-depcfg-pilot

  # ImageStream (pilot)
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: publicapi-api-pilot
      labels:
        app: publicapi-api-pilot

  # BuildConfig using Docker build strategy
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: publicapi-api-build-pilot
      labels:
        app: publicapi-api-pilot
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: pilot
        contextDir: .
      strategy:
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/api/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-api-pilot:latest
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4

  # Deployment config (pilot)
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: publicapi-api-deployment-pilot
      labels:
        app: publicapi-api-pilot
    spec:
      selector:
        app: publicapi-api-pilot
        depcfg: publicapi-api-depcfg-pilot
      template:
        metadata:
          labels:
            app: publicapi-api-pilot
            depcfg: publicapi-api-depcfg-pilot
        spec:
          containers:
            - name: publicapi-api-container-pilot
              image: publicapi/publicapi-api-pilot
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - publicapi-api-container-pilot
            from:
              kind: ImageStreamTag
              name: publicapi-api-pilot:latest
      strategy:
        type: Rolling