# This file is part of the research.fi api
#
# Copyright 2024 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-qa
    template: publicapi-indexer-cronjob-qa
  name: publicapi-indexer-cronjob-qa
objects:
  # Recurring CronJob (qa)
  # Indexes db entities to ElasticSearch.
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: publicapi-indexer-cronjob-qa
    spec:
      schedule: "0 2 * * *" # every day at 02:00 UTC
      concurrencyPolicy: "Forbid"
      startingDeadlineSeconds: 300 # Can start 5 minutes after the schedule  
      suspend: false
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      jobTemplate:
        spec:
          activeDeadlineSeconds: 2400 # Can run for 40 minutes
          template:
            spec:
              restartPolicy: Never
              containers:
                - name: publicapi-indexer-container-qa
                  image: publicapi-indexer-qa
                  imagePullPolicy: Always
                  env:
                    - name: "ELASTICSEARCH__PASSWORD"
                      valueFrom:
                        secretKeyRef:
                          name: publicapi-api-secret-qa
                          key: "ELASTICSEARCH__PASSWORD"
                    - name: "dbconnectionstring"
                      valueFrom:
                        secretKeyRef:
                          name: publicapi-api-secret-qa
                          key: dbconnectionstring
                    - name: "ELASTICSEARCH__URL"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "ELASTICSEARCH__URL"
                    - name: "ELASTICSEARCH__USERNAME"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "ELASTICSEARCH__USERNAME"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.FundingCall.FundingCall"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.FundingDecision.FundingDecision"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.Infrastructure.Infrastructure"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.Organization.Organization"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.ResearchDataset.ResearchDataset"
                    - name: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "IndexNames__CSC.PublicApi.Service.Models.Publication.Publication"
                    - name: "Serilog__MinimumLevel__Default"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "Serilog__MinimumLevel__Default"
                    - name: "Serilog__WriteTo__HttpSink__Args__requestUri"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "Serilog__WriteTo__HttpSink__Args__requestUri"
                    - name: "Serilog__Properties__WoodLogProjectNumber"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "Serilog__Properties__WoodLogProjectNumber"
                    - name: "Serilog__Properties__WoodLogRetentionMonthsIndexer"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "Serilog__Properties__WoodLogRetentionMonthsIndexer"
                    - name: "Serilog__Properties__WoodLogUsecaseIndexer"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "Serilog__Properties__WoodLogUsecaseIndexer"
                    - name: "QueryTimeout"
                      valueFrom:
                        configMapKeyRef:
                          name: publicapi-api-config-qa
                          key: "QueryTimeout"
