# This file is part of the research.fi api
#
# Copyright 2023 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-qa
    template: publicapi-indexer-manualjob-qa
  name: publicapi-indexer-manualjob-qa
  annotations:
    description: "Public API indexer QA - single-run Job"
    iconClass: icon-dotnet
objects:
  # Single-run Job (qa)
  # Use this job to index entities to ElasticSearch manually when needed.
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: publicapi-indexer-manualjob-qa
      labels:
        app: publicapi-indexer-qa
      annotations:
        description: Public API indexer QA - single-run Job
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: publicapi-indexer-manualjob-container-qa
              image: publicapi-indexer-qa
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: publicapi-api-secret-qa
                - configMapRef:
                    name: publicapi-api-config-qa
              resources:
                limits:
                  cpu: 500m
                  memory: 3Gi
                requests:
                  cpu: 100m
                  memory: 1Gi
