# This file is part of the research.fi api
#
# Copyright 2024 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-devel
    template: publicapi-indexer-devel
  name: publicapi-indexer-devel
  annotations:
    description: "Public API indexer devel"
    iconClass: icon-dotnet
objects:

  # ImageStream
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: publicapi-indexer-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      lookupPolicy:
        local: true

  # BuildConfig using Docker build strategy
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: publicapi-indexer-build-devel
      labels:
        app: publicapi-indexer-devel
    spec:
      source:
        git:
          uri: https://github.com/CSCfi/research-fi-publicapi.git
          ref: devel
        contextDir: .
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: aspnetcore/openshift/indexer/rahti2/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: publicapi-indexer-devel:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
