# This file is part of the research.fi api
#
# Copyright 2024 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: publicapi-indexer-production
    template: publicapi-indexer-cronjob-production
  name: publicapi-indexer-cronjob-production
  annotations:
    description: "Public API indexer production - CronJob"
    iconClass: icon-dotnet
objects:
  # Recurring CronJob (production)
  # Indexes db entities to ElasticSearch.
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: publicapi-indexer-cronjob-production
    spec:
      schedule: "40 19 * * *" # every day at 19:40 UTC
      concurrencyPolicy: "Forbid"
      startingDeadlineSeconds: 300 # Can start 5 minutes after the schedule
      suspend: false
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      jobTemplate:
        spec:
          activeDeadlineSeconds: 2400 # Can run for 40 minutes
          template:
            spec:
              restartPolicy: Never
              containers:
                - name: publicapi-indexer-container-production
                  image: publicapi-indexer-production
                  imagePullPolicy: Always
                  envFrom:
                    - secretRef:
                      name: publicapi-api-secret-production
                    - configMapRef:
                      name: publicapi-api-config-production
                  resources:
                    limits:
                      cpu: 500m
                      memory: 3Gi
                    requests:
                      cpu: 100m
                      memory: 1Gi
                      